const questions = [{
    QuesNo:1,
    questionText: 'What is the capital of France?',
    answerOptions: [
        { answerText: 'New York', isCorrect: false,option:'A' },
        { answerText: 'London', isCorrect: false,option:'B'},
        { answerText: 'Paris', isCorrect: true,option:'C'},
        { answerText: 'Dublin', isCorrect: false,option:'D' },
    ],
},
{   QuesNo:2,
    questionText: 'Who is CEO of Tesla?',
    answerOptions: [
        { answerText: 'Jeff Bezos', isCorrect: false,option:'A' },
        { answerText: 'Elon Musk', isCorrect: true ,option:'B'},
        { answerText: 'Bill Gates', isCorrect: false,option:'C' },
        { answerText: 'Tony Stark', isCorrect: false,option:'D' },
    ],
},
{QuesNo:3,
    questionText: 'The iPhone was created by which company?',
    answerOptions: [
        { answerText: 'Apple', isCorrect: true,option:'A' },
        { answerText: 'Intel', isCorrect: false,option:'B' },
        { answerText: 'Amazon', isCorrect: false,option:'C' },
        { answerText: 'Microsoft', isCorrect: false,option:'D'},
    ],
},
{QuesNo:4,
    questionText: 'How many Harry Potter books are there?',
    answerOptions: [
        { answerText: '1', isCorrect: false,option:'A' },
        { answerText: '4', isCorrect: false,option:'B' },
        { answerText: '6', isCorrect: false,option:'C' },
        { answerText: '7', isCorrect: true,option:'D' },
    ],
},{ QuesNo:5,
    questionText: 'What is the capital of France?',
    answerOptions: [
        { answerText: 'New York', isCorrect: false,option:'A' },
        { answerText: 'London', isCorrect: false,option:'B'},
        { answerText: 'Paris', isCorrect: true,option:'C'},
        { answerText: 'Dublin', isCorrect: false,option:'D' },
    ],
},
{QuesNo:6,
    questionText: 'Who is CEO of Tesla?',
    answerOptions: [
        { answerText: 'Jeff Bezos', isCorrect: false,option:'A' },
        { answerText: 'Elon Musk', isCorrect: true ,option:'B'},
        { answerText: 'Bill Gates', isCorrect: false,option:'C' },
        { answerText: 'Tony Stark', isCorrect: false,option:'D' },
    ],
},
{QuesNo:7,
    questionText: 'The iPhone was created by which company?',
    answerOptions: [
        { answerText: 'Apple', isCorrect: true,option:'A' },
        { answerText: 'Intel', isCorrect: false,option:'B' },
        { answerText: 'Amazon', isCorrect: false,option:'C' },
        { answerText: 'Microsoft', isCorrect: false,option:'D'},
    ],
},
{QuesNo:8,
    questionText: 'How many Harry Potter books are there?',
    answerOptions: [
        { answerText: '1', isCorrect: false,option:'A' },
        { answerText: '4', isCorrect: false,option:'B' },
        { answerText: '6', isCorrect: false,option:'C' },
        { answerText: '7', isCorrect: true,option:'D' },
    ],
},{QuesNo:8,
    questionText: 'How many Harry Potter books are there?',
    answerOptions: [
        { answerText: '1', isCorrect: false,option:'A' },
        { answerText: '4', isCorrect: false,option:'B' },
        { answerText: '6', isCorrect: false,option:'C' },
        { answerText: '7', isCorrect: true,option:'D' },
    ],
},
];


export default questions
